steps:
- uses: manleydev/butler-publish-itchio-action@master
  env:
    BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
    CHANNEL: html5
    ITCH_GAME: ${{ secrets.ITCHIO_GAMEID }}
    ITCH_USER: ${{ secrets.ITCHIO_USERNAME }}
    PACKAGE: build/WebGL